[tool.poetry]
name = "api-service"
version = "0.1.0"
description = ""
authors = ["Ashish Kadian <akadian135@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["all"], version = "^0.115.14"}
python-dotenv = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
